name: community
description: A Socail Media platform

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  #
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  ## Theme Management
  dynamic_theme: ^1.0.1
  ## Route/Navigation Management
  fluro: ^1.5.0
  ## Generate Launcher Icons
  flutter_launcher_icons: ^0.7.2
  ## Splash Screen Dependencu
  splashscreen: ^1.2.0
  ## Dio - HTTP
  dio: ^2.1.7
  ## GraphQL Support
  graphql_flutter: ^1.1.1-beta.7
  ## Equatable - Handles equality of objects
  equatable: ^0.2.6


  # State Management
  # State Management will be managed using two systems: BLoC and Redux
  # Local State (mainly UI and small local changes to views etc) should be managed with the BLoC pattern
  # Global State (API network Requests, Global App Preference Store,
  # or things affecting the entire app) should be managed with Redux
  ## Redux - Global State
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0
  redux_persist_flutter:
    git:
      url: https://github.com/dali546/redux_persist.git
      path: packages/redux_persist_flutter
  ## BLoC - Local State
  flutter_bloc: ^0.20.0

  # Custom Nav Bar
  curved_navigation_bar: ^0.2.20

  # Refresher
  pull_to_refresh: ^1.4.5

  # Animation
  simple_animations: 1.3.0
  gradient_widgets: ^0.5.0
  flip_card: ^0.3.0
  flutter_form_builder: ^3.2.8



  #global_configuration: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/screen.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

## Temporary Fix for Flutter Icons crashing on generating images

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"